[Greeter]
background=/usr/share/backgrounds/guiburon/nh-apluto-wide-9-17-15-final_0.png
draw-user-tests=false
draw-grid=true
theme-name=Arc-Dark
icon-theme-name=Qogir-Dark
cursor-theme-name=Qogir-Dark
cursor-theme-size=24
show-a11y=false
show-power=false
test-color=#000000
